# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Thoughts on soft-wa.re
email: gs8f371tjt7i@opayq.com
description: A blog of various opinions and ideas on soft-wa.re development
#baseurl: "" # the subpath of your site, e.g. /blog
url: "https://soft-wa.re" # the base hostname & protocol for your site
google_analytics: G-EBYCG9JSN0
google_adsense: ca-pub-7409268344688826
include: [ ]
collections_dir: ./_posts

collections:
  physics:
    output: true
  project_outlines:
    output: false
  style_guides:
    output: true
  general_advice:
    output: true
  patterns:
    output: true
  tutorials:
    output: true
  conversations:
    output: true
    skip: true
  misc:
    output: true
  posts:
    skip: true

# Build settings
markdown: kramdown
exclude: [vendor, "*node_modules*"]

theme: jekyll-theme-hacker
show_downloads: true
